spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8090
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 86400

spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE"
  data:
    rest:
      base-path: /rest
  groovy:
    template:
      content-type: text/html
      prefix: io/mikael/talent/view/
      suffix: .tpl

spring.jpa.hibernate.ddl-auto: create-drop

# override the secrets in a local configuration file, such as application-default.yml

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: xxx
      clientSecret: xxx
      accessTokenUri: https://www.yammer.com/oauth2/access_token
      userAuthorizationUri: https://www.yammer.com/oauth2/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://www.yammer.com/api/v1/users/current.json
      preferTokenInfo: false
    sso:
      login-path: /login
