spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 86400

spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE"
  data:
    rest:
      base-path: /rest
  resources:
    chain:
      cache: false
