spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE"
  data:
    rest:
      base-path: /rest
  groovy:
    template:
      content-type: text/html
      prefix: io/mikael/talent/view/
      suffix: .tpl

spring.jpa.hibernate.ddl-auto: create-drop
