CREATE TABLE people (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  last_seen_at TIMESTAMP,
  username     VARCHAR(255),
  name         TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE skills (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tag         VARCHAR(255),
  name        VARCHAR(255),
  description TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE organizations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  parent_id   BIGINT REFERENCES organizations,
  name        VARCHAR(255),
  description TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE personal_abilities (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  skill_id                BIGINT REFERENCES skills,
  target_id               BIGINT REFERENCES people,
  created_at              TIMESTAMP,
  modified_at             TIMESTAMP,
  comment                 TEXT,
  level                   INTEGER,
  personal_interest_level DOUBLE,
  PRIMARY KEY (id)
);

CREATE TABLE projects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_id   BIGINT REFERENCES people,
  created_at  TIMESTAMP,
  updated_at  TIMESTAMP,
  begins_at   TIMESTAMP,
  ends_at     TIMESTAMP,
  status      INTEGER,
  country     VARCHAR(255),
  location    VARCHAR(255),
  name        VARCHAR(255),
  description TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE recommend_people_for_projects (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT REFERENCES projects,
  source_id  BIGINT REFERENCES people,
  target_id  BIGINT REFERENCES people,
  created_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE recommend_projects_to_people (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT REFERENCES projects,
  source_id  BIGINT REFERENCES people,
  target_id  BIGINT REFERENCES people,
  created_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE thumb_personal_abilities (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_id  BIGINT REFERENCES people,
  target_id  BIGINT REFERENCES personal_abilities,
  created_at TIMESTAMP,
  PRIMARY KEY (id)
);
