CREATE TABLE people (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  last_seen_at TIMESTAMP,
  username     VARCHAR(255),
  name         TEXT,
  title        TEXT,
  description  TEXT,
  locations    ARRAY,
  roles        ARRAY,
  skills       ARRAY,
  interests    ARRAY,
  picture_url  TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE skills (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tag         VARCHAR(255),
  name        VARCHAR(255),
  description TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE organizations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  parent_id   BIGINT REFERENCES organizations (id),
  name        VARCHAR(255),
  description TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE projects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_id   BIGINT REFERENCES people,
  created_at  TIMESTAMP,
  updated_at  TIMESTAMP,
  begins_at   TIMESTAMP,
  ends_at     TIMESTAMP,
  status      INTEGER,
  country     VARCHAR(255),
  location    VARCHAR(255),
  name        VARCHAR(255),
  description TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE personal_abilities (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  skill_id                BIGINT REFERENCES skills,
  target_id               BIGINT REFERENCES people,
  created_at              TIMESTAMP,
  modified_at             TIMESTAMP,
  comment                 TEXT,
  level                   INTEGER,
  personal_interest_level DOUBLE,
  PRIMARY KEY (id)
);

CREATE TABLE recommend_people_for_projects (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT REFERENCES projects,
  source_id  BIGINT REFERENCES people,
  target_id  BIGINT REFERENCES people,
  created_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE recommend_projects_to_people (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT REFERENCES projects,
  source_id  BIGINT REFERENCES people,
  target_id  BIGINT REFERENCES people,
  created_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE thumb_personal_abilities (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_id  BIGINT REFERENCES people,
  target_id  BIGINT REFERENCES personal_abilities,
  created_at TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE consultant_profile (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  target_id               BIGINT REFERENCES people,
  current_position        TEXT,
  professional_experience TEXT,
  main_role               TEXT,
  contact_linkedin        TEXT,
  contact_twitter         TEXT,
  contact_email           TEXT,
  contact_phone           TEXT,
  competencies            TEXT,
  tools                   TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE profile_assignments (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  target_id            BIGINT REFERENCES consultant_profile,
  assignment_beginning TIMESTAMP,
  assignment_end       TIMESTAMP,
  project_name         TEXT,
  customer_industry    TEXT,
  role_in_project      TEXT,
  description          TEXT,
  technologies         TEXT,
  methodologies        TEXT,
  customer_benefits    TEXT,
  reference            TEXT,
  PRIMARY KEY (id)
);
